version: '3.8'

services:
  frontend:
    build:
      context: ./certiRoute/frontend
    container_name: certiRoute-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./certiRoute/frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    restart: unless-stopped

  backend:
    build:
      context: ./certiRoute/backend
    container_name: certiRoute-backend
    ports:
      - "5000:5000"
    volumes:
      - ./certiRoute/backend:/app
      - /app/node_modules
      - certificate-data:/app/data
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    network_mode: "host"  # Required to detect local web servers
    cap_add:
      - NET_ADMIN       # Required for network scanning

  nginx:
    build:
      context: ./certiRoute/nginx
    container_name: certiRoute-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./certiRoute/nginx/conf:/etc/nginx/conf.d
      - ./certiRoute/nginx/ssl:/etc/nginx/ssl
      - ./certiRoute/nginx/logs:/var/log/nginx
    restart: unless-stopped

volumes:
  certificate-data:
    driver: local 